/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGrafica;

import com.ministerio.analisis.credito.DataBase;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dgc06
 */
public class SesionUsuario extends javax.swing.JFrame {

    /**
     * Creates new form SesionUsuario
     */
    DataBase db = null;

    public SesionUsuario(DataBase db) {
        this.db = db;
        initComponents();
        try {
            cargarDatoSession();
            cargarImagenes();
        } catch (SQLException ex) {
            Logger.getLogger(SesionUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void cargarDatoSession() throws SQLException {
        ResultSet rs = db.consulta("SELECT * FROM fecha_creacion");
        while (rs.next()) {
            System.out.println((String) rs.getObject(1));
            
            if ("EXCEL".equals((String) rs.getObject(1))) {
                 System.out.println("ENTRE");
                 fechaSubidaCredito.setText( (String)rs.getObject(2));
                 descripCredito.setText((String)rs.getObject(4));
            }
            if ("LIRESTO".equals((String) rs.getObject(1))) {
                 System.out.println("ENTRE LI");
                 fechSubidaLiresto.setText( (String)rs.getObject(2));
                 String fecha = (String)rs.getObject(3);
                 fecha = fecha.substring(1,fecha.length());
                 fechLiqLiresto.setText(fecha);
                 descripLiresto.setText((String)rs.getObject(4));
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        javax.swing.JButton jButton2 = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaSubidaCredito = new javax.swing.JLabel();
        descripCredito = new javax.swing.JLabel();
        descripLiresto = new javax.swing.JLabel();
        fechLiqLiresto = new javax.swing.JLabel();
        fechSubidaLiresto = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SI");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 130, 40));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("NO");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 130, 40));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel1.setText("¿Desea continuar con estos archivos cargados?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 380, 410, 20));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Posees los siguientes archivos cargados en el sistema");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 440, 20));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        fechaSubidaCredito.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fechaSubidaCredito.setText("fecha_subida:");
        jPanel1.add(fechaSubidaCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 200, -1));

        descripCredito.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripCredito.setText("descrip");
        jPanel1.add(descripCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 200, -1));

        descripLiresto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripLiresto.setText("descripcion");
        jPanel1.add(descripLiresto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 180, -1));

        fechLiqLiresto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fechLiqLiresto.setText("fecha_liq");
        jPanel1.add(fechLiqLiresto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 180, -1));

        fechSubidaLiresto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fechSubidaLiresto.setText("fecha_subida");
        jPanel1.add(fechSubidaLiresto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 180, -1));

        jlabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlabel.setText("Fecha de liquidacion:");
        jPanel1.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 200, -1));

        jlabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlabel1.setText("Fecha de subida:");
        jPanel1.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 200, -1));

        jlabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlabel2.setText("Fecha de subida:");
        jPanel1.add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            db.cleanDataBase();
            new FormInicio(db).setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(SesionUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Menu m = new Menu(db);
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel descripCredito;
    javax.swing.JLabel descripLiresto;
    javax.swing.JLabel fechLiqLiresto;
    javax.swing.JLabel fechSubidaLiresto;
    javax.swing.JLabel fechaSubidaCredito;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JPanel jPanel1;
    javax.swing.JLabel jlabel;
    javax.swing.JLabel jlabel1;
    javax.swing.JLabel jlabel2;
    // End of variables declaration//GEN-END:variables

    private void cargarImagenes() {
         String dirActual = System.getProperty("user.dir");

          jLabel3.setIcon(new javax.swing.ImageIcon(dirActual + "\\images\\doc60px.png"));
          jLabel4.setIcon(new javax.swing.ImageIcon(dirActual + "\\images\\doc60px.png"));
    }
}
